### ISSUE TITLE
Hashtag between word

### ISSUE THREAD

**Issue by ghost** [connrs/node-find-hashtags#2]
Hi

This module works perfectly but I wanna mention something which is causing me problem.

When user by mistake write something "like#This" it return me "ke#This". Either it shouldn't be treated as hashtag or do it like other hashtags

Regards

**Comment by connrs** [comment]
Hi @adeelarshad83,

Thanks for your interest in this project. This really wasn't something that I expected anyone to be interested in!

I can see the feature you're looking for so I'll see if I can implement it for you. Pull requests are always welcome and you're welcome to submit a fix.

## 

connrs

**Comment by connrs** [comment]
That didn't take long. I've published v1.0.1 to npm.
